/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expensesaccounts;

import com.mysql.jdbc.Connection;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author POND
 */
public class FrmFix_User extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmFix_User
     */
    public FrmFix_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dgvShow = new javax.swing.JTable();
        cmdAdd = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPassword = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUsername = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdClose = new javax.swing.JButton();

        setTitle("กำหนดสิทธ์การใช้งาน");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        dgvShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password"
            }
        ));
        dgvShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvShowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvShow);

        cmdAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file+1.png"))); // NOI18N
        cmdAdd.setText("เพิ่มข้อมูล");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-1.png"))); // NOI18N
        cmdDelete.setText("ลบข้อมูล");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        cmdEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit1.png"))); // NOI18N
        cmdEdit.setText("เเก้ไขข้อมูล");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txtPassword);

        jScrollPane2.setViewportView(txtUsername);

        jLabel1.setText("USERNAME :");

        jLabel2.setText("PASSWORD :");

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        cmdClose.setText("ปิด");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(cmdClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dgvShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvShowMouseClicked
        // TODO add your handling code here:
        try {
            int nSelect = dgvShow.getSelectedRow();
            String sUser = dgvShow.getValueAt(nSelect , 0).toString();
            String sPass = dgvShow.getValueAt(nSelect , 1).toString();

            txtUsername.setText(sUser);
            txtPassword.setText(sPass);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_dgvShowMouseClicked

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed

        //-------------Add DB--------------//
        try {
            // TODO add your handling code here:
            if (txtUsername.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก USERNAME ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;

            }

            if (txtPassword.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก PASSWORD ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;
            }
            String sUser = txtUsername.getText().trim();
            String sPass = txtPassword.getText().trim();

            String sSql = "Insert Into bnuser(log_user, log_pass) Values ('"+sUser+"', '"+sPass+"')";

            PreparedStatement pre = jh_center.con.prepareStatement(sSql);

            if (pre.executeUpdate() != -1) {
                JOptionPane.showMessageDialog(rootPane, " เพิ่มเรียบร้อย ", "ตรวจสอบ",JOptionPane.INFORMATION_MESSAGE, null);
            }

            Wprv_ShowData();

            txtUsername.setText("");
            txtPassword.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage().toString(), "ตรวจสอบ",JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (txtUsername.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก USERNAME ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;
            }
            
            if (txtPassword.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก PASSWORD ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;
            }

            if (JOptionPane.showConfirmDialog(this, " ต้องการลบ  ใช่/ไม่ ","ตรวจสอบ", JOptionPane.YES_NO_OPTION ) == JOptionPane.NO_OPTION) {
                return;
            }
            if (jh_center.pssUsername.equals(txtUsername.getText().trim())) {
                JOptionPane.showMessageDialog(rootPane, " ไม่สามรลบได้ เพราะใช้งานอยู่ ", "ตรวจสอบ",JOptionPane.INFORMATION_MESSAGE, null); 
                return;
            }
            
//            if (jh_center.pssUsername == "admin") {
//                JOptionPane.showMessageDialog(rootPane, " ไม่สามรลบ Admin ได้ ", "ตรวจสอบ",JOptionPane.INFORMATION_MESSAGE, null);
//                
//            }

            String sUser = txtUsername.getText().trim();

            String sSql = " Delete From bnuser Where log_user = '"+sUser+"' ";

            PreparedStatement pre = jh_center.con.prepareStatement(sSql);

            if (pre.executeUpdate() != -1) {
                JOptionPane.showMessageDialog(rootPane, " ลบเรียบร้อย ", "ตรวจสอบ",JOptionPane.INFORMATION_MESSAGE, null);
            }

            Wprv_ShowData();

            txtUsername.setText("");
            txtPassword.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage().toString(), "ตรวจสอบ",JOptionPane.ERROR_MESSAGE, null);
        }

    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if (txtUsername.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก USERNAME ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;
            }
            if (txtPassword.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก PASSWORD ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;
            }
            String sUser = txtUsername.getText().trim();
            String sPass = txtPassword.getText().trim();
            
            String sSql = " Update bnuser Set log_pass = '"+sPass+"' Where log_user = '"+sUser+"' ";
            
            PreparedStatement pre = jh_center.con.prepareStatement(sSql);
            
            if (pre.executeUpdate() != -1) {
                JOptionPane.showMessageDialog(rootPane, " เเก้ไขเรียบร้อย ", "ตรวจสอบ",JOptionPane.INFORMATION_MESSAGE, null);     
            }
            
            Wprv_ShowData();
            
            txtUsername.setText("");
            txtPassword.setText("");
            
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage().toString(), "ตรวจสอบ",JOptionPane.ERROR_MESSAGE, null);  
            }    
         
    }//GEN-LAST:event_cmdEditActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            Wprv_ShowData();
        } catch (Exception ex) {
            //Logger.getLogger(FrmDB.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage().toString());  
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed

     private void Wprv_ShowData(){
        try {
            //-------------Show DB--------------//
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel = (DefaultTableModel) dgvShow.getModel();
            
            //------------ลบเเถว-------------//
            int nRowDel = dgvShow.getRowCount()-1; //ดูว่าในตรางมีกี่เเถวเเลว้เก็บใน  nRowDel
            while(nRowDel > -1){
                tableModel.removeRow(nRowDel);
                nRowDel --;
            }
            //-----------------------------//
            
            String sSql;
            String sUser, sPass;
            Object[] oData = new Object[0];
            sSql = "select * from bnuser";
            ResultSet rs = jh_center.con.createStatement().executeQuery(sSql);
            
            int nRow = 0;
            while(rs.next()){
                sUser = rs.getString("log_user");
                sPass = rs.getString("log_pass");
                
                System.out.println(sUser+" "+sPass);
                
                tableModel.addRow(oData);
                dgvShow.setValueAt(sUser, nRow, 0);
                dgvShow.setValueAt(sPass, nRow, 1);
                nRow++;
            }   
        } catch (Exception ex) {
        } 
     }      

     //

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JTable dgvShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txtPassword;
    private javax.swing.JTextPane txtUsername;
    // End of variables declaration//GEN-END:variables
}
