/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expensesaccounts;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
/**
 *
 * @author POND
 */
public class FrmInOut extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInOut
     */
    public FrmInOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtpDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        rdbIn = new javax.swing.JRadioButton();
        rdbOut = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        cmdType = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetil = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        lblDocNo = new javax.swing.JLabel();
        cmdSave = new javax.swing.JButton();
        cmdClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvShow = new javax.swing.JTable();
        chkDocNo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        dtpSearch = new org.jdesktop.swingx.JXDatePicker();
        cmdScarch = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("เอกสาร รายรับ - รายจ่าย");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("วันที่");

        jLabel2.setText("รับ/จ่าย");

        buttonGroup1.add(rdbIn);
        rdbIn.setSelected(true);
        rdbIn.setText("รายรับ");
        rdbIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbInMouseClicked(evt);
            }
        });

        buttonGroup1.add(rdbOut);
        rdbOut.setText("รายจ่าย");
        rdbOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOutActionPerformed(evt);
            }
        });

        jLabel3.setText("รายการ");

        cmdType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search2.png"))); // NOI18N
        cmdType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTypeActionPerformed(evt);
            }
        });

        jLabel4.setText("จำนวนเงิน");

        jLabel5.setText("หมายเหตุ");

        txtDetil.setColumns(20);
        txtDetil.setRows(5);
        jScrollPane1.setViewportView(txtDetil);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rdbIn)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbOut))
                                    .addComponent(dtpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(45, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dtpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdbIn)
                    .addComponent(rdbOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdType, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cmbType)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel6.setText("เลขที่เอกสาร");

        lblDocNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDocNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDocNo.setText("DocNo");
        lblDocNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDocNo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        cmdSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        cmdSave.setText("บันทึก");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        cmdClose.setText("ปิด");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        dgvShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "เลขที่เอกสาร", "วันที่", "รายการ", "จำนวนเงิน", "สานะ"
            }
        ));
        dgvShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvShowMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dgvShow);

        chkDocNo.setText("เอกสารประจำวัน");
        chkDocNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkDocNoMouseClicked(evt);
            }
        });

        jLabel7.setText("ค้าหาวันที่ทำรายการ");

        cmdScarch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search2.png"))); // NOI18N
        cmdScarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdScarchActionPerformed(evt);
            }
        });

        cmdDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        cmdDelete.setText("ลบ");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clean2.png"))); // NOI18N
        jButton1.setText("ล้าง");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblDocNo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(cmdClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkDocNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtpSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdScarch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkDocNo)
                            .addComponent(jLabel7)
                            .addComponent(dtpSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdScarch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblDocNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Wprv_ShowDataType();
        lblDocNo.setText(Wprv_AutoRun());
        Wprv_ShowData("Where datecreate='"+datDate.format(dNow).toString().trim()+"'");
        chkDocNo.setText("เอกสารประจำวันที่ : "+ datDateTitle.format(dNow).toString().trim() );
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void rdbInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbInMouseClicked
        // TODO add your handling code here:
        Wprv_ShowDataType();
    }//GEN-LAST:event_rdbInMouseClicked

    private void rdbOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOutActionPerformed
        // TODO add your handling code here:
        Wprv_ShowDataType();
    }//GEN-LAST:event_rdbOutActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        // TODO add your handling code here:
        //-------------Add DB--------------//
        try {
            if (cmbType.getSelectedItem().toString().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก ประเภทบิล ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;

            }

            if (txtAmount.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "กรุณากรอก จำนวนเงิน ", "ตรวจสอบ",JOptionPane.WARNING_MESSAGE, null);
                return;
            }
            
            //-------------dateinout------------------//
             formatter = new  SimpleDateFormat("yyyy/MM/dd");
             dateFormat = dtpDate.getDate();
             resultDateFrom =  formatter.format(dateFormat);
             //---------------------------------------//
             
             
             //----------amountstatus , status---------------// 
             double dAmount =0; //รายรับเป็น + ,รายจ่ายเป็น -
             String sStatus = ""; //ถ้าเป็นรายรับเป็น 1 , รายจ่ายเป็น 2
             if (rdbIn.isSelected() ==true) {
                 dAmount = Double.parseDouble(txtAmount.getText().trim());
                 sStatus = "1";
            }else{
                 dAmount = Double.parseDouble(txtAmount.getText().trim())*(-1);
                 sStatus = "2";
            }
             //-----------------------------------------//
             

            String sSql = " Insert Into bninout(docno, dateinout, typeinout, detail, amount, amountstatus, status, datecreate) "
                        + " Values ('"+lblDocNo.getText().trim()+"', '"+resultDateFrom+"', '"+cmbType.getSelectedItem().toString().trim()+"', "
                        + " '"+txtDetil.getText().trim()+"', "+txtAmount.getText().trim()+", "+dAmount+", '"+sStatus+"', '"+datDate.format(dNow).toString().trim()+"' ) ";

            PreparedStatement pre = jh_center.con.prepareStatement(sSql);

            if (pre.executeUpdate() != -1) {
                JOptionPane.showMessageDialog(rootPane, " เพิ่มเรียบร้อย ", "ตรวจสอบ",JOptionPane.INFORMATION_MESSAGE, null);
            }

            Wprv_ShowData(" Where datecreate ='"+datDate.format(dNow).toString().trim()+"' ");

            txtAmount.setText("");
            txtDetil.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage().toString(), "ตรวจสอบ",JOptionPane.ERROR_MESSAGE, null);
        }
        
        lblDocNo.setText(Wprv_AutoRun());
                         
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, " ต้องการลบ  ใช่/ไม่ ","ตรวจสอบ", JOptionPane.YES_NO_OPTION ) == JOptionPane.NO_OPTION) {
                return;
            }           

            String sSql = " Delete From bninout Where docno = '"+lblDocNo.getText().trim()+"' ";
            PreparedStatement pre = jh_center.con.prepareStatement(sSql);

            if (pre.executeUpdate() != -1) {
                JOptionPane.showMessageDialog(rootPane, " ลบเรียบร้อย ", "ตรวจสอบ",JOptionPane.INFORMATION_MESSAGE, null);
            }

            Wprv_ShowData(" Where datecreate ='"+datDate.format(dNow).toString().trim()+"' ");

            lblDocNo.setText(Wprv_AutoRun());
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage().toString(), "ตรวจสอบ",JOptionPane.ERROR_MESSAGE, null);
        }

     
    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lblDocNo.setText(Wprv_AutoRun());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dgvShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvShowMouseClicked
        // TODO add your handling code here:
        try {
            int nSelect = dgvShow.getSelectedRow();
            String sDocNo = dgvShow.getValueAt(nSelect , 0).toString();

            lblDocNo.setText(sDocNo);

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_dgvShowMouseClicked

    private void chkDocNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkDocNoMouseClicked
        // TODO add your handling code here:
        if (chkDocNo.isSelected() == true) {
            chkDocNo.setText("เอกสารทั้งหมด");
            Wprv_ShowData("");    
        }else{
            Wprv_ShowData("Where datecreate ='"+datDate.format(dNow).toString().trim()+"'");
            chkDocNo.setText("เอกสารทั้งหมด : "+datDateTitle.format(dNow).toString().trim());
        }
    }//GEN-LAST:event_chkDocNoMouseClicked

    private void cmdScarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdScarchActionPerformed
        // TODO add your handling code here:
        Wprv_ShowData(" Where datecreate ='"+datDate.format(dtpSearch.getDate()).toString().trim()+"' ");
    }//GEN-LAST:event_cmdScarchActionPerformed

    private void cmdTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTypeActionPerformed
        // TODO add your handling code here:
        FrmType frmType = new FrmType(null, true);
        if (rdbIn.isSelected() == true) {
            frmType.psChect ="1";
        }else{
            frmType.psChect = "2";
        }
        frmType.setModal(true);
        jh_center.Cprv_ScreenFormDialog(frmType);

        Wprv_ShowDataType();
    }//GEN-LAST:event_cmdTypeActionPerformed
   //------------------เกียวกับวัน-------------------------//
    DateFormat datDate = new SimpleDateFormat("yyyy/MM/dd");
    DateFormat datDateTitle = new SimpleDateFormat("dd/MM/yyyy");
    Date dateFormat;
    String resultDateFrom;
    SimpleDateFormat formatter;
    
    Date dNow = new Date();
    //------------------------------------------------//
    
    
    String sCheck ="";
    //method showDataType
     private void Wprv_ShowDataType(){
        try {
            cmbType.removeAllItems();
            
            if (rdbIn.isSelected() == true) {
                sCheck ="1";       
            }else{
                sCheck="2";
            }
            String sSql;
            String sName;
            Object[] oData = new Object[0];
            sSql = "select * from bntypereceive Where status ='"+sCheck+"'";
            ResultSet rs = jh_center.con.createStatement().executeQuery(sSql);
            
            int nRow = 0;
            while(rs.next()){
                sName = rs.getString("name");
                cmbType.addItem(sName);
                nRow++;
            }   
        } catch (Exception ex) {
            
        } 
     }  
     
     //method Auto Run (เลขที่เอกสาร)
     private String Wprv_AutoRun(){  
         String sDocNo ="";
        try {
            
            Date dNow = new Date();
            DateFormat datMonth = new SimpleDateFormat("MM");
            DateFormat datYear = new SimpleDateFormat("yy");
            
            int nId = 0;
            String sHead = "Doc"+ datYear.format(dNow).trim()+ datMonth.format(dNow); //Doc1812
            String sId = "";
            DecimalFormat df1 = new DecimalFormat("0000"); //Doc1812
            
            String sSql;
            Object[] oData = new Object[0];
            sSql = "select * from bninout Where docno Like '%"+sHead+"%' Order by docno desc";
            ResultSet rs = jh_center.con.createStatement().executeQuery(sSql);

            if(rs.next()){
                sId = rs.getString("docno"); //Doc18120001
                sId = sId.replace(sHead, ""); //0001
                
                nId = Integer.parseInt(sId)+1; //0001 ---> 1+1=2
                sDocNo = sHead+df1.format(nId); //0000 --->0002 =Doc18120002
            }else{
                nId = Integer.parseInt("0000")+1;
                sDocNo = sHead + df1.format(nId);
            }
            return sDocNo;
            
        } catch (Exception ex) {
            return sDocNo;    
        } 
     }
    
    //-------------- โชว์ข้อมูล --------------------//
     private void Wprv_ShowData(String _sSqlWhere){
        try {
            //-------------Show DB--------------//
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel = (DefaultTableModel) dgvShow.getModel();
            
            //------------ลบเเถว-------------//
            int nRowDel = dgvShow.getRowCount()-1; //ดูว่าในตรางมีกี่เเถวเเลว้เก็บใน  nRowDel
            while(nRowDel > -1){
                tableModel.removeRow(nRowDel);
                nRowDel --;
            }
            //-----------------------------//
            
            String sSql;
            String sDocno, sDateInOnt, sTypenInOut, sAmount, sStatus ;
            Object[] oData = new Object[0];
            sSql = "select docno, dateinout, typeinout, amount, "
                 + "CASE WHEN status='1' THEN 'รายรับ' ELSE 'รายจ่าย' End As status from bninout " + _sSqlWhere + " " +
                    " Order by docno desc";
                   
            ResultSet rs = jh_center.con.createStatement().executeQuery(sSql);
            
            int nRow = 0;
            while(rs.next()){
                sDocno = rs.getString("docno");
                sDateInOnt = rs.getString("dateinout");
                sTypenInOut = rs.getString("typeinout");
                sAmount = rs.getString("amount");
                sStatus = rs.getString("status");
           
                
//                System.out.println(sUser+" "+sPass);
                
                tableModel.addRow(oData);
                dgvShow.setValueAt(sDocno, nRow, 0);
                dgvShow.setValueAt(sDateInOnt, nRow, 1);
                dgvShow.setValueAt(sTypenInOut, nRow, 2);
                dgvShow.setValueAt(sAmount, nRow, 3);
                dgvShow.setValueAt(sStatus, nRow, 4);
                nRow++;
            }   
        } catch (Exception ex) {
        } 
     }      
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkDocNo;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdSave;
    private javax.swing.JButton cmdScarch;
    private javax.swing.JButton cmdType;
    private javax.swing.JTable dgvShow;
    private org.jdesktop.swingx.JXDatePicker dtpDate;
    private org.jdesktop.swingx.JXDatePicker dtpSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDocNo;
    private javax.swing.JRadioButton rdbIn;
    private javax.swing.JRadioButton rdbOut;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtDetil;
    // End of variables declaration//GEN-END:variables
}
