/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expensesaccounts;

import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author POND
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnConfig = new javax.swing.JMenu();
        mnLimit = new javax.swing.JMenuItem();
        mnDoc = new javax.swing.JMenu();
        mnInOut = new javax.swing.JMenuItem();
        mnReport = new javax.swing.JMenu();
        mnReportDay = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout dskMainLayout = new javax.swing.GroupLayout(dskMain);
        dskMain.setLayout(dskMainLayout);
        dskMainLayout.setHorizontalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        dskMainLayout.setVerticalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        mnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        mnConfig.setText("กำหนดค่า");

        mnLimit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user+.png"))); // NOI18N
        mnLimit.setText("กำหนดสิทธ์การใช้งาน");
        mnLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLimitActionPerformed(evt);
            }
        });
        mnConfig.add(mnLimit);

        jMenuBar1.add(mnConfig);

        mnDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file.png"))); // NOI18N
        mnDoc.setText("จัดการเอกสาร");

        mnInOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file+.png"))); // NOI18N
        mnInOut.setText("ลงบันทึก รายรับ-รายจ่าย");
        mnInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInOutActionPerformed(evt);
            }
        });
        mnDoc.add(mnInOut);

        jMenuBar1.add(mnDoc);

        mnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        mnReport.setText("รายงาน");

        mnReportDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report+.png"))); // NOI18N
        mnReportDay.setText("รายงานประจำวัน");
        mnReportDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReportDayActionPerformed(evt);
            }
        });
        mnReport.add(mnReportDay);

        jMenuBar1.add(mnReport);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jMenu1.setText("ออกจากโปรเเกรม");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //สั่งให้ จอเต็มหน้าจอ
        Dimension dimSceen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dimSceen.width, dimSceen.height);
        
//         try {
//            
//            //-------------Connect DB--------------//
//            String sConnect = "jdbc:mysql://localhost/db_money?characterEncodeing=YTF-8&useSSL=false";
//            Class.forName("com.mysql.jdbc.Driver");
//            
//            jh_center.con = (Connection) DriverManager.getConnection(sConnect, "root", "password");
//            
//            System.out.println("Connect DB OK!!");
//            
//        } catch (Exception ex) {
//            //Logger.getLogger(FrmDB.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(ex.getMessage().toString());  
//        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "คุณต้องการออกจากโปนแกรม  ใช่ / ไม่  ", "ตรวจสอบ", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;   
        }
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void mnLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLimitActionPerformed
        // TODO add your handling code here:
        try{
            FrmFix_User frmFix_User = new FrmFix_User();
            if (jh_center.psjinPageFix != null) {
                jh_center.psjinPageFix.dispose();   
            }
            jh_center.psjinPageFix = frmFix_User;
            Wprv_ScreenForm(frmFix_User, jh_center.psbpageFix);
            dskMain.add(frmFix_User);
        }catch(Exception ex){
        }
    }//GEN-LAST:event_mnLimitActionPerformed

    private void mnInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInOutActionPerformed
        // TODO add your handling code here:
         try{
            FrmInOut frmInOut = new FrmInOut();
            if (jh_center.psjinPageInOut != null) {
                jh_center.psjinPageInOut.dispose();   
            }
            jh_center.psjinPageInOut = frmInOut;
            Wprv_ScreenForm(frmInOut, jh_center.psbPageInOut);
            dskMain.add(frmInOut);
        }catch(Exception ex){
        }
    }//GEN-LAST:event_mnInOutActionPerformed

    private void mnReportDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReportDayActionPerformed
        // TODO add your handling code here:
        try{
            FrmReportDay frmReportDay = new FrmReportDay();
            if (jh_center.psjinPageReportDay != null) {
                jh_center.psjinPageReportDay.dispose();   
            }
            jh_center.psjinPageInOut = frmReportDay;
            Wprv_ScreenForm(frmReportDay, jh_center.psbPageRepostDay);
            dskMain.add(frmReportDay);
        }catch(Exception ex){
        }
    }//GEN-LAST:event_mnReportDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }
    
    //open from child
     private void Wprv_ScreenForm(JInternalFrame _Frm, boolean  _bCheck){
         Dimension dimScreen = Toolkit.getDefaultToolkit().getScreenSize();
         
         int nWidth = _Frm.getSize().width;
         int nHeigth = _Frm.getSize().height;
         
         int nSreenX = (dimScreen.width-nWidth)/2;
         int nSreenY = ((dimScreen.height-nHeigth)/2-90);
         
         _Frm.setLocation(nSreenX, nSreenY);
         _Frm.setVisible(_bCheck);
     }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnConfig;
    private javax.swing.JMenu mnDoc;
    private javax.swing.JMenuItem mnInOut;
    private javax.swing.JMenuItem mnLimit;
    private javax.swing.JMenu mnReport;
    private javax.swing.JMenuItem mnReportDay;
    // End of variables declaration//GEN-END:variables
}
